apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-mysql
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: confidential
              key: sqlrootpassword
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: confidential
              key: sqluser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: confidential
              key: sqlpassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: confidential
              key: sqldb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-ps
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-ps
        persistentVolumeClaim:
          claimName: mysql